/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pattern;

import pattern.builder.experiment.Student;

public class Main {
    public static void main(String[] args) {
        Student s1 = new Student();
        s1.experiment();
    }
}

//public static void command() {
//    Student s1 = new Student();
//    s1.experiment();
//}