/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pattern;

import pattern.observer.school.ObserverSchoolMain;

public class Main {
    public static void main(String[] args) {
//        Student s1 = new Student();
//        s1.experiment();
        ObserverSchoolMain main = new ObserverSchoolMain();
        main.execute();
    }
}