@startuml Strategy.Human.Class

Human *-- Comparator

interface Comparator {
    int compare(Human, Human)
}

class AgeComparator implements Comparator
class HeightComparator implements Comparator
class WeightComparator implements Comparator

class Human {
}

@enduml