@startuml Observer.Study.Class

abstract class Student {
    Teacher[] teacherList
    void addTeacher(Teacher)
    void notifyTeachers()
}
interface Teacher {
    void update()
}

class MathTeacher implements Teacher
class EnglishTeacher implements Teacher
class PhisicsTeacher implements Teacher

class Student1 {
    void studyEnglish()
    void studyMath()
}

class Student2 {
    void studyEnglish()
    void studyPhisics()
}

Student1 --|> Student
Student2 --|> Student

Student o--> Teacher

@enduml